info:
  contact: {}
paths:
  /bocchi/access_token/get:
    get:
      consumes:
      - json/form
      description: get available access-token by refresh-token
      parameters:
      - description: refresh-token
        in: header
        name: refresh-token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: get_access-token
  /bocchi/party/apply:
    get:
      consumes:
      - json/form
      description: apply to join the party
      parameters:
      - description: 活动id
        in: query
        name: party_id
        required: true
        type: integer
      - description: access-token
        in: header
        name: access-token
        required: true
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: apply_party
  /bocchi/party/apply/list:
    get:
      consumes:
      - json/form
      description: show party's applicants
      parameters:
      - description: 活动id
        in: query
        name: party_id
        required: true
        type: integer
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: access-token
        in: header
        name: access-token
        required: true
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: apply_list
  /bocchi/party/apply/permit:
    get:
      consumes:
      - json/form
      description: permit user to join the party
      parameters:
      - description: 活动id
        in: query
        name: party_id
        required: true
        type: integer
      - description: 用户id
        in: query
        name: member_id
        required: true
        type: integer
      - description: access-token
        in: header
        name: access-token
        required: true
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: permit_join
  /bocchi/party/create:
    post:
      consumes:
      - json/form
      description: create party
      parameters:
      - description: 标题
        in: query
        name: title
        required: true
        type: string
      - description: 介绍
        in: query
        name: content
        required: true
        type: string
      - description: 类型
        in: query
        name: type
        required: true
        type: integer
      - description: 活动省份
        in: query
        name: province
        required: true
        type: string
      - description: 活动城市
        in: query
        name: city
        required: true
        type: string
      - description: 开始时间(例:2006-01-02)
        in: query
        name: start_time
        required: true
        type: string
      - description: 结束时间(例:2006-01-02)
        in: query
        name: end_time
        required: true
        type: string
      - description: access-token
        in: header
        name: access-token
        required: true
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: create_party
  /bocchi/party/members:
    get:
      consumes:
      - json/form
      description: get members who have join the party
      parameters:
      - description: 活动id
        in: query
        name: party_id
        required: true
        type: integer
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: get_party_members
  /bocchi/party/search:
    post:
      consumes:
      - json/form
      description: search party
      parameters:
      - description: 搜索内容
        in: query
        name: content
        type: string
      - description: 活动类型
        in: query
        name: party_type
        type: string
      - description: 活动省份
        in: query
        name: province
        type: string
      - description: 活动城市
        in: query
        name: city
        type: string
      - description: 几天后开始
        in: query
        name: start_time_duration
        type: integer
      - description: 搜索方式(0:默认;1:按开始时间;2:按活动已有人数)
        in: query
        name: search_type
        type: integer
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: search_party
  /bocchi/user/avatar/upload:
    put:
      consumes:
      - json/form
      description: revise user's avatar
      parameters:
      - description: 头像
        in: formData
        name: avatar_file
        required: true
        type: file
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: PutAvatar
  /bocchi/user/info:
    get:
      consumes:
      - json/form
      description: get user's info
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Info
  /bocchi/user/login/:
    post:
      consumes:
      - json/form
      description: login to get your auth token
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: otp
        in: query
        name: otp
        type: string
      produces:
      - application/json
      responses: {}
      summary: Login
  /bocchi/user/register/:
    post:
      consumes:
      - json/form
      description: userRegister
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Register
  /bocchi/user/signature:
    post:
      consumes:
      - json/form
      description: revise signature
      parameters:
      - description: signature
        in: query
        name: signature
        required: true
        type: string
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: signature
  /bocchi/user/switch2fa:
    post:
      consumes:
      - json/form
      description: switch on/off 2fa mode
      parameters:
      - description: 关闭:0;开启:1
        in: query
        name: action_type
        required: true
        type: integer
      - description: totp
        in: query
        name: totp
        type: string
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: switch_2fa
swagger: "2.0"
