// Code generated by Kitex v0.9.1. DO NOT EDIT.

package partyhandler

import (
	party "bocchi/kitex_gen/party"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateParty": kitex.NewMethodInfo(
		createPartyHandler,
		newPartyHandlerCreatePartyArgs,
		newPartyHandlerCreatePartyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"JoinParty": kitex.NewMethodInfo(
		joinPartyHandler,
		newPartyHandlerJoinPartyArgs,
		newPartyHandlerJoinPartyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApplyList": kitex.NewMethodInfo(
		applyListHandler,
		newPartyHandlerApplyListArgs,
		newPartyHandlerApplyListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PermitJoin": kitex.NewMethodInfo(
		permitJoinHandler,
		newPartyHandlerPermitJoinArgs,
		newPartyHandlerPermitJoinResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPartyInfo": kitex.NewMethodInfo(
		getPartyInfoHandler,
		newPartyHandlerGetPartyInfoArgs,
		newPartyHandlerGetPartyInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPartyMembers": kitex.NewMethodInfo(
		getPartyMembersHandler,
		newPartyHandlerGetPartyMembersArgs,
		newPartyHandlerGetPartyMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchParty": kitex.NewMethodInfo(
		searchPartyHandler,
		newPartyHandlerSearchPartyArgs,
		newPartyHandlerSearchPartyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMyParties": kitex.NewMethodInfo(
		getMyPartiesHandler,
		newPartyHandlerGetMyPartiesArgs,
		newPartyHandlerGetMyPartiesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	partyHandlerServiceInfo                = NewServiceInfo()
	partyHandlerServiceInfoForClient       = NewServiceInfoForClient()
	partyHandlerServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return partyHandlerServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return partyHandlerServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return partyHandlerServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PartyHandler"
	handlerType := (*party.PartyHandler)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "party",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func createPartyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*party.PartyHandlerCreatePartyArgs)
	realResult := result.(*party.PartyHandlerCreatePartyResult)
	success, err := handler.(party.PartyHandler).CreateParty(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPartyHandlerCreatePartyArgs() interface{} {
	return party.NewPartyHandlerCreatePartyArgs()
}

func newPartyHandlerCreatePartyResult() interface{} {
	return party.NewPartyHandlerCreatePartyResult()
}

func joinPartyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*party.PartyHandlerJoinPartyArgs)
	realResult := result.(*party.PartyHandlerJoinPartyResult)
	success, err := handler.(party.PartyHandler).JoinParty(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPartyHandlerJoinPartyArgs() interface{} {
	return party.NewPartyHandlerJoinPartyArgs()
}

func newPartyHandlerJoinPartyResult() interface{} {
	return party.NewPartyHandlerJoinPartyResult()
}

func applyListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*party.PartyHandlerApplyListArgs)
	realResult := result.(*party.PartyHandlerApplyListResult)
	success, err := handler.(party.PartyHandler).ApplyList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPartyHandlerApplyListArgs() interface{} {
	return party.NewPartyHandlerApplyListArgs()
}

func newPartyHandlerApplyListResult() interface{} {
	return party.NewPartyHandlerApplyListResult()
}

func permitJoinHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*party.PartyHandlerPermitJoinArgs)
	realResult := result.(*party.PartyHandlerPermitJoinResult)
	success, err := handler.(party.PartyHandler).PermitJoin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPartyHandlerPermitJoinArgs() interface{} {
	return party.NewPartyHandlerPermitJoinArgs()
}

func newPartyHandlerPermitJoinResult() interface{} {
	return party.NewPartyHandlerPermitJoinResult()
}

func getPartyInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*party.PartyHandlerGetPartyInfoArgs)
	realResult := result.(*party.PartyHandlerGetPartyInfoResult)
	success, err := handler.(party.PartyHandler).GetPartyInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPartyHandlerGetPartyInfoArgs() interface{} {
	return party.NewPartyHandlerGetPartyInfoArgs()
}

func newPartyHandlerGetPartyInfoResult() interface{} {
	return party.NewPartyHandlerGetPartyInfoResult()
}

func getPartyMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*party.PartyHandlerGetPartyMembersArgs)
	realResult := result.(*party.PartyHandlerGetPartyMembersResult)
	success, err := handler.(party.PartyHandler).GetPartyMembers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPartyHandlerGetPartyMembersArgs() interface{} {
	return party.NewPartyHandlerGetPartyMembersArgs()
}

func newPartyHandlerGetPartyMembersResult() interface{} {
	return party.NewPartyHandlerGetPartyMembersResult()
}

func searchPartyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*party.PartyHandlerSearchPartyArgs)
	realResult := result.(*party.PartyHandlerSearchPartyResult)
	success, err := handler.(party.PartyHandler).SearchParty(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPartyHandlerSearchPartyArgs() interface{} {
	return party.NewPartyHandlerSearchPartyArgs()
}

func newPartyHandlerSearchPartyResult() interface{} {
	return party.NewPartyHandlerSearchPartyResult()
}

func getMyPartiesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*party.PartyHandlerGetMyPartiesArgs)
	realResult := result.(*party.PartyHandlerGetMyPartiesResult)
	success, err := handler.(party.PartyHandler).GetMyParties(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPartyHandlerGetMyPartiesArgs() interface{} {
	return party.NewPartyHandlerGetMyPartiesArgs()
}

func newPartyHandlerGetMyPartiesResult() interface{} {
	return party.NewPartyHandlerGetMyPartiesResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateParty(ctx context.Context, req *party.CreatePartyRequest) (r *party.CreatePartyResponse, err error) {
	var _args party.PartyHandlerCreatePartyArgs
	_args.Req = req
	var _result party.PartyHandlerCreatePartyResult
	if err = p.c.Call(ctx, "CreateParty", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) JoinParty(ctx context.Context, req *party.JoinPartyRequest) (r *party.JoinPartyResponse, err error) {
	var _args party.PartyHandlerJoinPartyArgs
	_args.Req = req
	var _result party.PartyHandlerJoinPartyResult
	if err = p.c.Call(ctx, "JoinParty", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApplyList(ctx context.Context, req *party.ApplyListRequest) (r *party.ApplyListResponse, err error) {
	var _args party.PartyHandlerApplyListArgs
	_args.Req = req
	var _result party.PartyHandlerApplyListResult
	if err = p.c.Call(ctx, "ApplyList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PermitJoin(ctx context.Context, req *party.PermitJoinRequest) (r *party.PermitJoinResponse, err error) {
	var _args party.PartyHandlerPermitJoinArgs
	_args.Req = req
	var _result party.PartyHandlerPermitJoinResult
	if err = p.c.Call(ctx, "PermitJoin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPartyInfo(ctx context.Context, req *party.GetPartyInfoRequest) (r *party.GetPartyInfoResponse, err error) {
	var _args party.PartyHandlerGetPartyInfoArgs
	_args.Req = req
	var _result party.PartyHandlerGetPartyInfoResult
	if err = p.c.Call(ctx, "GetPartyInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPartyMembers(ctx context.Context, req *party.GetPartyMembersRequest) (r *party.GetPartyMembersResponse, err error) {
	var _args party.PartyHandlerGetPartyMembersArgs
	_args.Req = req
	var _result party.PartyHandlerGetPartyMembersResult
	if err = p.c.Call(ctx, "GetPartyMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchParty(ctx context.Context, req *party.SearchPartyRequest) (r *party.SearchPartyResponse, err error) {
	var _args party.PartyHandlerSearchPartyArgs
	_args.Req = req
	var _result party.PartyHandlerSearchPartyResult
	if err = p.c.Call(ctx, "SearchParty", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMyParties(ctx context.Context, req *party.GetMyPartiesRequest) (r *party.GetMyPartiesResponse, err error) {
	var _args party.PartyHandlerGetMyPartiesArgs
	_args.Req = req
	var _result party.PartyHandlerGetMyPartiesResult
	if err = p.c.Call(ctx, "GetMyParties", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
