// Code generated by hertz generator.

package api

import (
	api "bocchi/api/biz/model/api"
	"bocchi/api/biz/rpc"
	"bocchi/kitex_gen/trust"
	"bocchi/pkg/errno"
	"bocchi/pkg/pack"
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// TrustAction .
// @Summary trust_action
// @Description trust action
// @Accept json/form
// @Produce json
// @Param object_uid query int true "操作对象id"
// @Param action_type query int true "0：取消信任;1：信任"
// @Param access-token header string false "access-token"
// @Param refresh-token header string false "refresh-token"
// @router /bibi/trust/action [POST]
func TrustAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FollowActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.FollowActionResponse)

	v, _ := c.Get("current_user_id")
	id := v.(int64)
	if req.ObjectUID == id {
		resp.Base = pack.ConvertToAPIBaseResp(pack.BuildBaseResp(errno.FollowMyselfError))
		c.JSON(consts.StatusOK, resp)
		return
	}
	rpcResp, err := rpc.FollowAction(ctx, &trust.FollowActionRequest{
		ObjectUid:  req.ObjectUID,
		ActionType: req.ActionType,
		UserId:     id,
	})
	if err != nil {
		pack.SendRPCFailResp(c, err)
	}
	resp.Base = pack.ConvertToAPIBaseResp(rpcResp.Base)
	c.JSON(consts.StatusOK, resp)
}

// FollowerList .
// @Summary follower_list
// @Description list who trust you
// @Accept json/form
// @Produce json
// @Param page_num query int64 true "页码"
// @router /bibi/trust/follower [GET]
func FollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FollowerListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.FollowerListResponse)

	rpcResp, err := rpc.FollowerList(ctx, &trust.FollowerListRequest{
		PageNum: req.PageNum,
		UserId:  req.UserID,
	})
	if err != nil {
		pack.SendRPCFailResp(c, err)
	}
	resp.Base = pack.ConvertToAPIBaseResp(rpcResp.Base)
	if rpcResp.Base.Code != errno.SuccessCode {
		c.JSON(consts.StatusOK, resp)
	}
	resp.Count = rpcResp.Count
	resp.FollowerList = pack.ConvertToAPIUsers(rpcResp.FollowerList)
	c.JSON(consts.StatusOK, resp)
}

// FollowingList .
// @Summary following_list
// @Description list who you trusted
// @Accept json/form
// @Produce json
// @Param page_num query int64 true "页码"
// @router /bibi/trust/following [GET]
func FollowingList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FollowingListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.FollowingListResponse)

	rpcResp, err := rpc.FollowingList(ctx, &trust.FollowingListRequest{
		PageNum: req.PageNum,
		UserId:  req.UserID,
	})
	if err != nil {
		pack.SendRPCFailResp(c, err)
	}
	resp.Base = pack.ConvertToAPIBaseResp(rpcResp.Base)
	if rpcResp.Base.Code != errno.SuccessCode {
		c.JSON(consts.StatusOK, resp)
	}
	resp.Count = rpcResp.Count
	resp.FollowingList = pack.ConvertToAPIUsers(rpcResp.FollowingList)
	c.JSON(consts.StatusOK, resp)
}

// TrustEachList .
// @Summary friend_list
// @Description list your friends
// @Accept json/form
// @Produce json
// @Param page_num query int64 true "页码"
// @Param access-token header string false "access-token"
// @Param refresh-token header string false "refresh-token"
// @router /bibi/trust/each [POST]
func TrustEachList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FriendListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.FriendListResponse)

	v, _ := c.Get("current_user_id")
	id := v.(int64)
	rpcResp, err := rpc.FriendList(ctx, &trust.FriendListRequest{
		PageNum: req.PageNum,
		UserId:  id,
	})
	if err != nil {
		pack.SendRPCFailResp(c, err)
	}
	resp.Base = pack.ConvertToAPIBaseResp(rpcResp.Base)
	if rpcResp.Base.Code != errno.SuccessCode {
		c.JSON(consts.StatusOK, resp)
	}
	resp.Count = rpcResp.Count
	resp.FriendList = pack.ConvertToAPIUsers(rpcResp.FriendList)
	c.JSON(consts.StatusOK, resp)
}
