version: '3'



services:
  mysql:
    image: mysql:8.0.36
    container_name: bocchi-the-travel
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3366:3306"
    environment:
      - MYSQL_DATABASE=bocchi_db
      - MYSQL_ROOT_PASSWORD=114514
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge

  redis:
    image: redis:6.0.16
    container_name: redis
    ports:
      - "6399:6379"
    volumes:
      - ./data/redis/data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/logs:/logs
    restart: always
    network_mode: bridge


  etcd:
    image: bitnami/etcd:3.5
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./pkg/data/etcd/data:/bitnami/etcd-data
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    network_mode: bridge

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      xpack.security.enabled: "false"
      xpack.security.enrollment.enabled: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m" # 加大内存设置
      discovery.type: single-node
      TZ: Asia/Shanghai
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch/config:/usr/share/elasticsearch/config
      - ./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
    network_mode: bridge

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    environment:
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana:/usr/share/kibana/config
      - ./data/kibana:/usr/share/kibana/data
    network_mode: bridge