// Code generated by Kitex v0.9.1. DO NOT EDIT.

package followhandler

import (
	trust "bocchi/kitex_gen/trust"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"TrustAction": kitex.NewMethodInfo(
		trustActionHandler,
		newFollowHandlerTrustActionArgs,
		newFollowHandlerTrustActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FollowerList": kitex.NewMethodInfo(
		followerListHandler,
		newFollowHandlerFollowerListArgs,
		newFollowHandlerFollowerListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FollowingList": kitex.NewMethodInfo(
		followingListHandler,
		newFollowHandlerFollowingListArgs,
		newFollowHandlerFollowingListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TrustEachList": kitex.NewMethodInfo(
		trustEachListHandler,
		newFollowHandlerTrustEachListArgs,
		newFollowHandlerTrustEachListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	followHandlerServiceInfo                = NewServiceInfo()
	followHandlerServiceInfoForClient       = NewServiceInfoForClient()
	followHandlerServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return followHandlerServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return followHandlerServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return followHandlerServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "FollowHandler"
	handlerType := (*trust.FollowHandler)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "trust",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func trustActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trust.FollowHandlerTrustActionArgs)
	realResult := result.(*trust.FollowHandlerTrustActionResult)
	success, err := handler.(trust.FollowHandler).TrustAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowHandlerTrustActionArgs() interface{} {
	return trust.NewFollowHandlerTrustActionArgs()
}

func newFollowHandlerTrustActionResult() interface{} {
	return trust.NewFollowHandlerTrustActionResult()
}

func followerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trust.FollowHandlerFollowerListArgs)
	realResult := result.(*trust.FollowHandlerFollowerListResult)
	success, err := handler.(trust.FollowHandler).FollowerList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowHandlerFollowerListArgs() interface{} {
	return trust.NewFollowHandlerFollowerListArgs()
}

func newFollowHandlerFollowerListResult() interface{} {
	return trust.NewFollowHandlerFollowerListResult()
}

func followingListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trust.FollowHandlerFollowingListArgs)
	realResult := result.(*trust.FollowHandlerFollowingListResult)
	success, err := handler.(trust.FollowHandler).FollowingList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowHandlerFollowingListArgs() interface{} {
	return trust.NewFollowHandlerFollowingListArgs()
}

func newFollowHandlerFollowingListResult() interface{} {
	return trust.NewFollowHandlerFollowingListResult()
}

func trustEachListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trust.FollowHandlerTrustEachListArgs)
	realResult := result.(*trust.FollowHandlerTrustEachListResult)
	success, err := handler.(trust.FollowHandler).TrustEachList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowHandlerTrustEachListArgs() interface{} {
	return trust.NewFollowHandlerTrustEachListArgs()
}

func newFollowHandlerTrustEachListResult() interface{} {
	return trust.NewFollowHandlerTrustEachListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) TrustAction(ctx context.Context, req *trust.FollowActionRequest) (r *trust.FollowActionResponse, err error) {
	var _args trust.FollowHandlerTrustActionArgs
	_args.Req = req
	var _result trust.FollowHandlerTrustActionResult
	if err = p.c.Call(ctx, "TrustAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowerList(ctx context.Context, req *trust.FollowerListRequest) (r *trust.FollowerListResponse, err error) {
	var _args trust.FollowHandlerFollowerListArgs
	_args.Req = req
	var _result trust.FollowHandlerFollowerListResult
	if err = p.c.Call(ctx, "FollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowingList(ctx context.Context, req *trust.FollowingListRequest) (r *trust.FollowingListResponse, err error) {
	var _args trust.FollowHandlerFollowingListArgs
	_args.Req = req
	var _result trust.FollowHandlerFollowingListResult
	if err = p.c.Call(ctx, "FollowingList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TrustEachList(ctx context.Context, req *trust.FriendListRequest) (r *trust.FriendListResponse, err error) {
	var _args trust.FollowHandlerTrustEachListArgs
	_args.Req = req
	var _result trust.FollowHandlerTrustEachListResult
	if err = p.c.Call(ctx, "TrustEachList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
