server:
  addr: 127.0.0.1:8000
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 114514
  dbname: bibi_db
redis:
  addr: 127.0.0.1:6379
service:
  mode: debug
  port: :8888
oss:
  endpoint:
  accesskeyid:
  accesskeysecret:
  bucketname:
  main-directory:
page:
  page-size: 15
rabbitmq:
  port: 5672
  name: guest
  password: guest
email:
  sender:
  password:
  from: bibi-demo<sender email>
  subject: your OTP