server:
  jwt-secret: bocchi-the-rock
  version: "debug"
  name: bocchi
  cors: "https://bocchi-the-travel.com"
etcd:
  addr: 127.0.0.1:2389

mysql:
  addr: 127.0.0.1:3366
  user: root
  password: 114514
  database: bocchi_db

redis:
  addr: 127.0.0.1:6399

oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  accesskeyid:
  accesskeysecret:
  bucketname:
  main-directory:

rabbitmq:
  addr: 127.0.0.1:5672
  user: guest
  password: guest

email:
  host: smtp.qq.com
  port: 25
  sender:
  password:
  from:
  subject:

elasticsearch:
  addr: 127.0.0.1:9200
  host: 127.0.0.1

services:
  api:
    name: api
    load-balance: false
    addr:
      - 127.0.0.1:10001
  user:
    name: user
    load-balance: false
    addr:
      - 127.0.0.1:10002
  party:
    name: party
    load-balance: false
    addr:
      - 127.0.0.1:10003
  itinerary:
    name: itinerary
    load-balance: false
    addr:
      - 127.0.0.1:10004